name: CI WorkFlows

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actioin/checkout@v4

      - name: Run a test script
        run: echo "WorkFlows Triggered Successfully"
